CREATE DATABASE VETERINARIA_DW;
USE VETERINARIA_DW;

CREATE TABLE EMPLEADOS(
EmpleadoId int identity(1,1) primary key,
Nombre nvarchar(100) ,
Apellido nvarchar(100) ,
Position nvarchar(100) ,
Email nvarchar(100),
)

CREATE TABLE CLIENTES(
ID_CLIENTE INT IDENTITY(1,1) PRIMARY KEY,
CEDULA VARCHAR(20),
NOMBRE VARCHAR(50),
APELLIDO VARCHAR(50),
TELEFONO varchar(50),
DIRECCION VARCHAR(100),
CORREO VARCHAR(100)
);

CREATE TABLE MASCOTAS(
ID_MASCOTA INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE VARCHAR(50),
RAZA VARCHAR(50),
PADECIMIENTO VARCHAR(50),
EDAD INT,
);

CREATE TABLE CATEGORIAS(
ID_CATEGORIA INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_CATEGORIA VARCHAR(100),
);

CREATE TABLE PRODUCTOS(
ID_PRODUCTO INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_PRODUCTO VARCHAR(100),
DESCRIPCCION  VARCHAR(100)
);

CREATE TABLE TRATAMIENTOS(
ID_TRATAMIENTO INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_TRATAMIENTO VARCHAR(100)
);

CREATE TABLE OPERACIONES(
ID_OPERACION INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_OPERACION VARCHAR(100)
);

CREATE TABLE PROOVEDORES(
ID_PROOVEDOR INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_PROOVEDOR VARCHAR(150),
TELEFONO VARCHAR(50)
);

CREATE TABLE VETERINARIAS
(ID_VETERINARIA INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_VETERINARIA VARCHAR(50),
DESC_VETERINARIA VARCHAR(150)
);

CREATE TABLE CANTONES(
ID_CANTON INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_CANTON VARCHAR(50))

CREATE TABLE PROVINCIAS(
ID_PROVINCIA INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_PROVINCIA VARCHAR(50)
);

CREATE TABLE TIEMPO(
ID_TIEMPO INT IDENTITY(1,1) PRIMARY KEY,
ANIO INT,
TRIMESTRE INT,
MES INT,
DIA INT)

CREATE TABLE TOTAL(
ID_TOTAL INT IDENTITY(1,1) PRIMARY KEY,
ID_EMPLEADO INT,
ID_CLIENTE INT,
ID_MASCOTA INT,
ID_CATEGORIA INT,
ID_PRODUCTO INT,
ID_TRATAMIENTO INT,
ID_OPERACION INT,
ID_PROOVEDOR INT,
ID_VETERINARIA INT,
ID_CANTON INT,
ID_PROVINCIA INT,
ID_TIEMPO INT,

PRECIO_PRODUCTO FLOAT,
PRECIO_OPERACION FLOAT,
PRECIO_TRATAMIENTO FLOAT,
CANTIDAD_PRODUCTO INT

CONSTRAINT RELACION_A_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(EmpleadoId),
CONSTRAINT RELACION_A_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
CONSTRAINT RELACION_A_MASCOTA FOREIGN KEY (ID_MASCOTA) REFERENCES MASCOTAS(ID_MASCOTA),
CONSTRAINT RELACION_A_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA),
CONSTRAINT RELACION_A_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO),
CONSTRAINT RELACION_A_TRATAMIENTO FOREIGN KEY (ID_TRATAMIENTO) REFERENCES TRATAMIENTOS(ID_TRATAMIENTO),
CONSTRAINT RELACION_A_OPERACION FOREIGN KEY (ID_OPERACION) REFERENCES OPERACIONES(ID_OPERACION),
CONSTRAINT RELACION_A_PROOVEDOR FOREIGN KEY (ID_PROOVEDOR) REFERENCES PROOVEDORES(ID_PROOVEDOR),
CONSTRAINT RELACION_A_VETERINARIA FOREIGN KEY (ID_VETERINARIA) REFERENCES VETERINARIAS(ID_VETERINARIA),
CONSTRAINT RELACION_A_CANTON FOREIGN KEY (ID_CANTON) REFERENCES CANTONES(ID_CANTON),
CONSTRAINT RELACION_A_PROVINCIA FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIAS(ID_PROVINCIA),
CONSTRAINT RELACION_A_TIEMPO FOREIGN KEY (ID_TIEMPO) REFERENCES TIEMPO(ID_TIEMPO),
)

--Inserts
insert into EMPLEADOS 
values
('Jose',
'Padilla',
'Doctor',
'j@gmail.com')

insert into TRATAMIENTOS
values
('Effitix pipetas antiparasitarias'),
('Aceite Grizzly de Salmón'),
('Four Paws Brewers Yeast con ajo'),
('Tabletas para perros y gatos'),
('Potty Mouth'),
('Crema Paw Guard'),
('Ear Wash 4 Oz'),
('Ear Powder 24 Gramos'),
('Hemostatico Gel 1.16 Oz'),
('Dosificador Para Pastillas'),
('Tratamiento para impedir la Coprofagia');

insert into OPERACIONES
values
('Cirugía oncológica'),
('Operación de la vista'),
('Cirugía digestiva'),
('Cirugía traumatológica'),
('Operación de hernias'),
('Cirugía del aparato urinario'),
('Cirugía odontológica');

insert into CATEGORIAS
values
('NINGUNO'),
('Alimentación'),
('Arenas'),
('Accesorios, Correas, Collares'),
('Bebederos y Comederos'),
('Camas'),
('Cepillos y Baño'),
('Rascadero y Postes'),
('Literas, Arena y Palas'),
('Juguetes'),
('Jaulas y Transportadoras'),
('Salud'),
('Medicamentos'),
('Ropa'),
('Antipulgas');